OLLAMA_BASE_URL = "http://localhost:11434"
LLM_MODEL = "qwen3:14b"
EMBEDDING_MODEL = "bge-m3"
EMBEDDING_DIM = 1024

QDRANT_MODE = "local"  # "local" | "memory"
QDRANT_HOST = "localhost"
QDRANT_PORT = 6333
QDRANT_COLLECTION = "mentor_knowledge"

WEIGHT_MOMENTUM = 0.35
MIN_WEIGHT_THRESHOLD = 0.05
TOPIC_SIMILARITY_THRESHOLD = 0.45

EMBEDDING_SCORE_WEIGHT = 0.6
DOMAIN_SCORE_WEIGHT = 0.4

TRAJECTORY_WINDOW = 3
TRAJECTORY_BONUS = 0.10

COUNCIL_TOP_N = 4
COUNCIL_MIN_SCORE_GAP = 0.15

QDRANT_SEARCH_LIMIT = 5
